"use strict";
exports.__esModule = true;
var circle_1 = require("./circle");
var rectangle_1 = require("./rectangle");
var circleobj = new circle_1.Circle(3);
circleobj.Myarea();
circleobj.dispaly();
var rectobj = new rectangle_1.Rectangle(2, 3);
rectobj.Myarea();
rectobj.display();
